## Series

In [1]:
import pandas as pd

numbers = [1,2,3,4]

series_test = pd.Series(numbers)

series_test

0    1
1    2
2    3
3    4
dtype: int64

In [2]:
series_test_2 = pd.Series({1999: 48, 
                           2000: 100, 
                           2010: 1000})
series_test_2

1999      48
2000     100
2010    1000
dtype: int64

## Dataframes

In [3]:
frame_test = pd.DataFrame({1999: [10,40,24,0],
                           2000: [11,44,20,1],
                           2001: [12,35,24,6]})
frame_test

   1999  2000  2001
0    10    11    12
1    40    44    35
2    24    20    24
3     0     1     6

In [4]:
frame_test2 = pd.DataFrame([[10,40,24,0],
                           [11,44,20,1],
                           [12,35,24,6]], columns=[1998,1999,2000,2001])
frame_test2

   1998  1999  2000  2001
0    10    40    24     0
1    11    44    20     1
2    12    35    24     6

## Read data

In [5]:
pd.options.display.max_rows = 10

csv_test = pd.read_csv('convertcsv.csv')
type(csv_test)
# csv_test.head()
csv_test

,seq,name/first,name/last,age,street,city,state,zip,dollar,pick,date
0,1,Travis,Coleman,44,Jeeno Circle,Radsoapi,CA,70599,$4091.43,YELLOW,01/03/1957
1,2,Stella,Stevenson,20,Lamer Parkway,Densirkar,ID,95119,$4692.19,RED,12/27/2031
2,3,Lula,Jacobs,53,Jorku Plaza,Kalbacroh,WI,78844,$9836.09,GREEN,05/19/2034
3,4,Bertie,Walsh,22,Hujat Boulevard,Gocbagrem,MA,47488,$239.81,YELLOW,10/04/1924
4,5,Mathilda,Mack,48,Cogsi Grove,Gonajsik,OK,24414,$8221.91,GREEN,09/19/1917
...,...,...,...,...,...,...,...,...,...,...,...
95,96,Rhoda,Montgomery,58,Rete River,Vuzeuv,FL,30858,$1048.31,BLUE,04/18/1924
96,97,Jack,Robbins,39,Farel Drive,Untovcep,CO,48520,$9098.80,RED,11/04/2045
97,98,Allie,Hodges,29,Nuctoc Terrace,Notsafa,SD,4837,$4032.25,BLUE,02/02/1972
98,99,Martin,Maxwell,46,Fejlo Square,Mifiwpop,NH,88050,$6525.67,WHITE,11/13/2037
99,100,Ann,Estrada,39,Rokof Lane,Cuojsad,KY,94182,$3391.26,YELLOW,03/21/1908

## Reading data from et_dataset

In [6]:
csv_test_et = pd.read_csv('web_scraper/eltiempo_2020_02_14_articles.csv')
type(csv_test_et)
# csv_test_et.head()
csv_test_et

,body,title,url
0,Un año después del atentado contra la Escuela ...,Un año del ataque del terrorismo contra el cor...,https://www.eltiempo.com/justicia/investigacio...
1,"Cecilia Torres Santos, de 80 años, fue secuest...",Liberan a mujer de 80 años que duró secuestrad...,https://www.eltiempo.com/colombia/otras-ciudad...
2,¿Se ha preguntado alguna vez cómo sería vivir ...,Recorra con nosotros los 5 puntos más extremos...,https://www.eltiempo.com/colombia/otras-ciudad...
3,Los colombianos en Wuhan serán evacuados el pr...,Colombianos en Wuhan serán evacuados el 22 de ...,https://www.eltiempo.com/politica/gobierno/col...
4,"Carlos Montaño, integrante del dueto Siam; Jua...",Los 'hombres a la plancha' también tienen su c...,https://www.eltiempo.com/cultura/arte-y-teatro...
...,...,...,...
73,La defensa de Harvey Weinstein pidió este juev...,Defensa de Weinstein pide al jurado que sea 'v...,https://www.eltiempo.com/mundo/eeuu-y-canada/a...
74,En el mundo gerencial y empresarial hay una pr...,NaN,https://www.guiaacademica.com/noticias/posgrad...
75,\n\n\n\n\n\nELN\n\n02:25 p.m. \n\n\n\n\n ...,\nSan Valentín y los memes que rompieron las r...,https://www.eltiempo.com/vida/viajar/hoteles-p...
76,\n\n\n\n\n\ncarro\n\n12:49 p.m. \n\n\n\n\n ...,\nSan Valentín y los memes que rompieron las r...,https://www.eltiempo.com/mundo/mas-regiones/pu...
77,\n\n\n\n\n\nMúsica\n\n02:30 p.m. \n\n\n\n\n ...,Escasez de sangre en hospitales y bancos de Ca...,https://www.eltiempo.com/colombia/cali/llamado...

## Index and selection

In [7]:
# dictionary like 

csv_test_et['title'] 

# if you want to select more than one column, you can add it to array. ex: csv_test_et[['title', 'body']]

0     Un año del ataque del terrorismo contra el cor...
1     Liberan a mujer de 80 años que duró secuestrad...
2     Recorra con nosotros los 5 puntos más extremos...
3     Colombianos en Wuhan serán evacuados el 22 de ...
4     Los 'hombres a la plancha' también tienen su c...
                            ...
73    Defensa de Weinstein pide al jurado que sea 'v...
74                                                  NaN
75    \nSan Valentín y los memes que rompieron las r...
76    \nSan Valentín y los memes que rompieron las r...
77    Escasez de sangre en hospitales y bancos de Ca...
Name: title, Length: 78, dtype: object

In [8]:
csv_test_et[['title', 'body']]

,title,body
0,Un año del ataque del terrorismo contra el cor...,Un año después del atentado contra la Escuela ...
1,Liberan a mujer de 80 años que duró secuestrad...,"Cecilia Torres Santos, de 80 años, fue secuest..."
2,Recorra con nosotros los 5 puntos más extremos...,¿Se ha preguntado alguna vez cómo sería vivir ...
3,Colombianos en Wuhan serán evacuados el 22 de ...,Los colombianos en Wuhan serán evacuados el pr...
4,Los 'hombres a la plancha' también tienen su c...,"Carlos Montaño, integrante del dueto Siam; Jua..."
...,...,...
73,Defensa de Weinstein pide al jurado que sea 'v...,La defensa de Harvey Weinstein pidió este juev...
74,NaN,En el mundo gerencial y empresarial hay una pr...
75,\nSan Valentín y los memes que rompieron las r...,\n\n\n\n\n\nELN\n\n02:25 p.m. \n\n\n\n\n ...
76,\nSan Valentín y los memes que rompieron las r...,\n\n\n\n\n\ncarro\n\n12:49 p.m. \n\n\n\n\n ...
77,Escasez de sangre en hospitales y bancos de Ca...,\n\n\n\n\n\nMúsica\n\n02:30 p.m. \n\n\n\n\n ...

In [9]:
# Numpy like 

csv_test_et.iloc[10:15]

,body,title,url
10,"Aunque la emergencia ya había sido controlada,...","Alerta por incendio forestal en Guasca, Cundin...",https://www.eltiempo.com/bogota/incendio-fores...
11,En su primera declaración como nuevo fiscal ge...,Nuevo Fiscal reabre debate sobre inhabilidad p...,https://www.eltiempo.com/justicia/delitos/fisc...
12,El proyecto para revitalizar esta localidad de...,Anuncian cable aéreo y plan de vivienda para S...,https://www.eltiempo.com/bogota/cable-aereo-en...
13,\n\n\n\n\n\nELN\n\n02:25 p.m. \n\n\n\n\n ...,\nLos equipos excluidos por la Uefa de competi...,https://www.eltiempo.com/mundo/asia/coronaviru...
14,Autoridades confirmaron que cinco colombianos ...,Disidencias estarían detrás de masacre en la f...,https://www.eltiempo.com/justicia/conflicto-y-...

In [10]:
csv_test_et.iloc[66]['title']

'Tortuga más grande del planeta vivió en Colombia, Brasil y Venezuela'

In [11]:
csv_test_et.iloc[:5,0]

0    Un año después del atentado contra la Escuela ...
1    Cecilia Torres Santos, de 80 años, fue secuest...
2    ¿Se ha preguntado alguna vez cómo sería vivir ...
3    Los colombianos en Wuhan serán evacuados el pr...
4    Carlos Montaño, integrante del dueto Siam; Jua...
Name: body, dtype: object

In [12]:
csv_test_et.loc[:,'body':'title']

,body,title
0,Un año después del atentado contra la Escuela ...,Un año del ataque del terrorismo contra el cor...
1,"Cecilia Torres Santos, de 80 años, fue secuest...",Liberan a mujer de 80 años que duró secuestrad...
2,¿Se ha preguntado alguna vez cómo sería vivir ...,Recorra con nosotros los 5 puntos más extremos...
3,Los colombianos en Wuhan serán evacuados el pr...,Colombianos en Wuhan serán evacuados el 22 de ...
4,"Carlos Montaño, integrante del dueto Siam; Jua...",Los 'hombres a la plancha' también tienen su c...
...,...,...
73,La defensa de Harvey Weinstein pidió este juev...,Defensa de Weinstein pide al jurado que sea 'v...
74,En el mundo gerencial y empresarial hay una pr...,NaN
75,\n\n\n\n\n\nELN\n\n02:25 p.m. \n\n\n\n\n ...,\nSan Valentín y los memes que rompieron las r...
76,\n\n\n\n\n\ncarro\n\n12:49 p.m. \n\n\n\n\n ...,\nSan Valentín y los memes que rompieron las r...
77,\n\n\n\n\n\nMúsica\n\n02:30 p.m. \n\n\n\n\n ...,Escasez de sangre en hospitales y bancos de Ca...

## Data wrangling

In [13]:
# 1. Add newspaper_iud to DataFrame

csv_test_et['newspaper_iud'] = 'eltiempo'
csv_test_et

,body,title,url,newspaper_iud
0,Un año después del atentado contra la Escuela ...,Un año del ataque del terrorismo contra el cor...,https://www.eltiempo.com/justicia/investigacio...,eltiempo
1,"Cecilia Torres Santos, de 80 años, fue secuest...",Liberan a mujer de 80 años que duró secuestrad...,https://www.eltiempo.com/colombia/otras-ciudad...,eltiempo
2,¿Se ha preguntado alguna vez cómo sería vivir ...,Recorra con nosotros los 5 puntos más extremos...,https://www.eltiempo.com/colombia/otras-ciudad...,eltiempo
3,Los colombianos en Wuhan serán evacuados el pr...,Colombianos en Wuhan serán evacuados el 22 de ...,https://www.eltiempo.com/politica/gobierno/col...,eltiempo
4,"Carlos Montaño, integrante del dueto Siam; Jua...",Los 'hombres a la plancha' también tienen su c...,https://www.eltiempo.com/cultura/arte-y-teatro...,eltiempo
...,...,...,...,...
73,La defensa de Harvey Weinstein pidió este juev...,Defensa de Weinstein pide al jurado que sea 'v...,https://www.eltiempo.com/mundo/eeuu-y-canada/a...,eltiempo
74,En el mundo gerencial y empresarial hay una pr...,NaN,https://www.guiaacademica.com/noticias/posgrad...,eltiempo
75,\n\n\n\n\n\nELN\n\n02:25 p.m. \n\n\n\n\n ...,\nSan Valentín y los memes que rompieron las r...,https://www.eltiempo.com/vida/viajar/hoteles-p...,eltiempo
76,\n\n\n\n\n\ncarro\n\n12:49 p.m. \n\n\n\n\n ...,\nSan Valentín y los memes que rompieron las r...,https://www.eltiempo.com/mundo/mas-regiones/pu...,eltiempo
77,\n\n\n\n\n\nMúsica\n\n02:30 p.m. \n\n\n\n\n ...,Escasez de sangre en hospitales y bancos de Ca...,https://www.eltiempo.com/colombia/cali/llamado...,eltiempo

In [14]:
# 2. Get host
from urllib.parse import urlparse

csv_test_et['host'] = csv_test_et['url'].apply(lambda url: urlparse(url).netloc)
csv_test_et

,body,title,url,newspaper_iud,host
0,Un año después del atentado contra la Escuela ...,Un año del ataque del terrorismo contra el cor...,https://www.eltiempo.com/justicia/investigacio...,eltiempo,www.eltiempo.com
1,"Cecilia Torres Santos, de 80 años, fue secuest...",Liberan a mujer de 80 años que duró secuestrad...,https://www.eltiempo.com/colombia/otras-ciudad...,eltiempo,www.eltiempo.com
2,¿Se ha preguntado alguna vez cómo sería vivir ...,Recorra con nosotros los 5 puntos más extremos...,https://www.eltiempo.com/colombia/otras-ciudad...,eltiempo,www.eltiempo.com
3,Los colombianos en Wuhan serán evacuados el pr...,Colombianos en Wuhan serán evacuados el 22 de ...,https://www.eltiempo.com/politica/gobierno/col...,eltiempo,www.eltiempo.com
4,"Carlos Montaño, integrante del dueto Siam; Jua...",Los 'hombres a la plancha' también tienen su c...,https://www.eltiempo.com/cultura/arte-y-teatro...,eltiempo,www.eltiempo.com
...,...,...,...,...,...
73,La defensa de Harvey Weinstein pidió este juev...,Defensa de Weinstein pide al jurado que sea 'v...,https://www.eltiempo.com/mundo/eeuu-y-canada/a...,eltiempo,www.eltiempo.com
74,En el mundo gerencial y empresarial hay una pr...,NaN,https://www.guiaacademica.com/noticias/posgrad...,eltiempo,www.guiaacademica.com
75,\n\n\n\n\n\nELN\n\n02:25 p.m. \n\n\n\n\n ...,\nSan Valentín y los memes que rompieron las r...,https://www.eltiempo.com/vida/viajar/hoteles-p...,eltiempo,www.eltiempo.com
76,\n\n\n\n\n\ncarro\n\n12:49 p.m. \n\n\n\n\n ...,\nSan Valentín y los memes que rompieron las r...,https://www.eltiempo.com/mundo/mas-regiones/pu...,eltiempo,www.eltiempo.com
77,\n\n\n\n\n\nMúsica\n\n02:30 p.m. \n\n\n\n\n ...,Escasez de sangre en hospitales y bancos de Ca...,https://www.eltiempo.com/colombia/cali/llamado...,eltiempo,www.eltiempo.com

In [15]:
csv_test_et['host'].value_counts()

www.eltiempo.com         76
www.guiaacademica.com     1
www.portafolio.co         1
Name: host, dtype: int64

# Missing Data

In [16]:
# 3. Fill missing data

missing_titles_mask = csv_test_et['title'].isna()

# missing_titles_mask

missing_titles = (csv_test_et[missing_titles_mask]['url']
                     .str.extract(r'(?P<missing_titles>[^/]+)$')
                     .applymap(lambda title: title.split('-'))
                     .applymap(lambda title_word_list: ' '.join(title_word_list)))
missing_titles

                                       missing_titles
7   fin de las cortesias columna de eduardo posada...
29  para que la verdad columna de moises wasserman...
32  calcule cuanto le pagara su empresa por concep...
38              otra torpeza del eln editorial 461970
61  la justicia al servicio de la politica columna...
74  viaja estudia y capacitate con un executive mb...

# Additional cleanup

In [20]:
# 4. Add uid to files
import hashlib

uids = (csv_test_et
        .apply(lambda row: hashlib.md5(bytes(row['url'].encode())), axis=1)
        .apply(lambda hash_object: hash_object.hexdigest())
       )

csv_test_et['uid'] = uids
csv_test_et.set_index('uid', inplace=True)

csv_test_et

,body,title,url,newspaper_iud,host
uid,,,,,
1eeeaa1752c45bb31d57176b5578e139,Un año después del atentado contra la Escuela ...,Un año del ataque del terrorismo contra el cor...,https://www.eltiempo.com/justicia/investigacio...,eltiempo,www.eltiempo.com
4976c2c2e9d82f297eb8af62a26dbf9f,"Cecilia Torres Santos, de 80 años, fue secuest...",Liberan a mujer de 80 años que duró secuestrad...,https://www.eltiempo.com/colombia/otras-ciudad...,eltiempo,www.eltiempo.com
10b752489b82c704a543b4048e8a8340,¿Se ha preguntado alguna vez cómo sería vivir ...,Recorra con nosotros los 5 puntos más extremos...,https://www.eltiempo.com/colombia/otras-ciudad...,eltiempo,www.eltiempo.com
d86a58e8c7faec10640ed5bc74554eaa,Los colombianos en Wuhan serán evacuados el pr...,Colombianos en Wuhan serán evacuados el 22 de ...,https://www.eltiempo.com/politica/gobierno/col...,eltiempo,www.eltiempo.com
864ae848913430f182f9bb5fa8bf91d1,"Carlos Montaño, integrante del dueto Siam; Jua...",Los 'hombres a la plancha' también tienen su c...,https://www.eltiempo.com/cultura/arte-y-teatro...,eltiempo,www.eltiempo.com
...,...,...,...,...,...
df234650a39dc7ca9df67355bb780ca6,La defensa de Harvey Weinstein pidió este juev...,Defensa de Weinstein pide al jurado que sea 'v...,https://www.eltiempo.com/mundo/eeuu-y-canada/a...,eltiempo,www.eltiempo.com
2b931f3a8d6f4d60a381a06418a8a00f,En el mundo gerencial y empresarial hay una pr...,NaN,https://www.guiaacademica.com/noticias/posgrad...,eltiempo,www.guiaacademica.com
cfe7743c3d1dd60eb291b7a7a239d8e0,\n\n\n\n\n\nELN\n\n02:25 p.m. \n\n\n\n\n ...,\nSan Valentín y los memes que rompieron las r...,https://www.eltiempo.com/vida/viajar/hoteles-p...,eltiempo,www.eltiempo.com
f9206a142e4ed48ebdfca8ea3d30ca32,\n\n\n\n\n\ncarro\n\n12:49 p.m. \n\n\n\n\n ...,\nSan Valentín y los memes que rompieron las r...,https://www.eltiempo.com/mundo/mas-regiones/pu...,eltiempo,www.eltiempo.com
d752310af66ac114f1472bc85a9ba16a,\n\n\n\n\n\nMúsica\n\n02:30 p.m. \n\n\n\n\n ...,Escasez de sangre en hospitales y bancos de Ca...,https://www.eltiempo.com/colombia/cali/llamado...,eltiempo,www.eltiempo.com

In [23]:
stripped_body = (csv_test_et
                .apply(lambda row: row['body'],axis=1)
                .apply(lambda body: list(body))
                .apply(lambda letters: list(map(lambda letter: letter.replace('\n', ''), letters)))
                .apply(lambda letters: ''.join(letters))
                )

stripped_body

uid
1eeeaa1752c45bb31d57176b5578e139    Un año después del atentado contra la Escuela ...
4976c2c2e9d82f297eb8af62a26dbf9f    Cecilia Torres Santos, de 80 años, fue secuest...
10b752489b82c704a543b4048e8a8340    ¿Se ha preguntado alguna vez cómo sería vivir ...
d86a58e8c7faec10640ed5bc74554eaa    Los colombianos en Wuhan serán evacuados el pr...
864ae848913430f182f9bb5fa8bf91d1    Carlos Montaño, integrante del dueto Siam; Jua...
                                                          ...
df234650a39dc7ca9df67355bb780ca6    La defensa de Harvey Weinstein pidió este juev...
2b931f3a8d6f4d60a381a06418a8a00f    En el mundo gerencial y empresarial hay una pr...
cfe7743c3d1dd60eb291b7a7a239d8e0    ELN02:25 p.m.                             Este...
f9206a142e4ed48ebdfca8ea3d30ca32    carro12:49 p.m.                             Re...
d752310af66ac114f1472bc85a9ba16a    Música02:30 p.m.                             P...
Length: 78, dtype: object